import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/header";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";
import {HearderMsg} from "@/components/hearderMsg";

// const interTight = Inter_Tight({
//   subsets: ["latin"],
//   variable: "--font-inter-tight",
// });


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full","antialiased",inter.variable,playfair.variable)}
    >
      <body className="min-h-full flex flex-col relative bg-[#ffffff] font-inter">
        <Toaster></Toaster>
        <HearderMsg></HearderMsg>
        <Header></Header>
        <main className="relative">{children}</main>
      </body>
    </html>
  );
}
